/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUtentiRouteImport } from './routes/_authenticated/utenti'
import { Route as AuthenticatedServiziRouteImport } from './routes/_authenticated/servizi'
import { Route as AuthenticatedSerateRouteImport } from './routes/_authenticated/serate'
import { Route as AuthenticatedRuoliRouteImport } from './routes/_authenticated/ruoli'
import { Route as AuthenticatedCorseCavalliRouteImport } from './routes/_authenticated/corse-cavalli'
import { Route as AuthenticatedConversioniRouteImport } from './routes/_authenticated/conversioni'
import { Route as AuthenticatedCittadiniRouteImport } from './routes/_authenticated/cittadini'
import { Route as AuthenticatedCassetteRouteImport } from './routes/_authenticated/cassette'
import { Route as AuthenticatedBadgeRouteImport } from './routes/_authenticated/badge'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUtentiRoute = AuthenticatedUtentiRouteImport.update({
  id: '/utenti',
  path: '/utenti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiziRoute = AuthenticatedServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSerateRoute = AuthenticatedSerateRouteImport.update({
  id: '/serate',
  path: '/serate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRuoliRoute = AuthenticatedRuoliRouteImport.update({
  id: '/ruoli',
  path: '/ruoli',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorseCavalliRoute =
  AuthenticatedCorseCavalliRouteImport.update({
    id: '/corse-cavalli',
    path: '/corse-cavalli',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversioniRoute =
  AuthenticatedConversioniRouteImport.update({
    id: '/conversioni',
    path: '/conversioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCittadiniRoute = AuthenticatedCittadiniRouteImport.update({
  id: '/cittadini',
  path: '/cittadini',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCassetteRoute = AuthenticatedCassetteRouteImport.update({
  id: '/cassette',
  path: '/cassette',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBadgeRoute = AuthenticatedBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badge': typeof AuthenticatedBadgeRoute
  '/cassette': typeof AuthenticatedCassetteRoute
  '/cittadini': typeof AuthenticatedCittadiniRoute
  '/conversioni': typeof AuthenticatedConversioniRoute
  '/corse-cavalli': typeof AuthenticatedCorseCavalliRoute
  '/ruoli': typeof AuthenticatedRuoliRoute
  '/serate': typeof AuthenticatedSerateRoute
  '/servizi': typeof AuthenticatedServiziRoute
  '/utenti': typeof AuthenticatedUtentiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badge': typeof AuthenticatedBadgeRoute
  '/cassette': typeof AuthenticatedCassetteRoute
  '/cittadini': typeof AuthenticatedCittadiniRoute
  '/conversioni': typeof AuthenticatedConversioniRoute
  '/corse-cavalli': typeof AuthenticatedCorseCavalliRoute
  '/ruoli': typeof AuthenticatedRuoliRoute
  '/serate': typeof AuthenticatedSerateRoute
  '/servizi': typeof AuthenticatedServiziRoute
  '/utenti': typeof AuthenticatedUtentiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/badge': typeof AuthenticatedBadgeRoute
  '/_authenticated/cassette': typeof AuthenticatedCassetteRoute
  '/_authenticated/cittadini': typeof AuthenticatedCittadiniRoute
  '/_authenticated/conversioni': typeof AuthenticatedConversioniRoute
  '/_authenticated/corse-cavalli': typeof AuthenticatedCorseCavalliRoute
  '/_authenticated/ruoli': typeof AuthenticatedRuoliRoute
  '/_authenticated/serate': typeof AuthenticatedSerateRoute
  '/_authenticated/servizi': typeof AuthenticatedServiziRoute
  '/_authenticated/utenti': typeof AuthenticatedUtentiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/badge'
    | '/cassette'
    | '/cittadini'
    | '/conversioni'
    | '/corse-cavalli'
    | '/ruoli'
    | '/serate'
    | '/servizi'
    | '/utenti'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/badge'
    | '/cassette'
    | '/cittadini'
    | '/conversioni'
    | '/corse-cavalli'
    | '/ruoli'
    | '/serate'
    | '/servizi'
    | '/utenti'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/badge'
    | '/_authenticated/cassette'
    | '/_authenticated/cittadini'
    | '/_authenticated/conversioni'
    | '/_authenticated/corse-cavalli'
    | '/_authenticated/ruoli'
    | '/_authenticated/serate'
    | '/_authenticated/servizi'
    | '/_authenticated/utenti'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/utenti': {
      id: '/_authenticated/utenti'
      path: '/utenti'
      fullPath: '/utenti'
      preLoaderRoute: typeof AuthenticatedUtentiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servizi': {
      id: '/_authenticated/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof AuthenticatedServiziRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/serate': {
      id: '/_authenticated/serate'
      path: '/serate'
      fullPath: '/serate'
      preLoaderRoute: typeof AuthenticatedSerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ruoli': {
      id: '/_authenticated/ruoli'
      path: '/ruoli'
      fullPath: '/ruoli'
      preLoaderRoute: typeof AuthenticatedRuoliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corse-cavalli': {
      id: '/_authenticated/corse-cavalli'
      path: '/corse-cavalli'
      fullPath: '/corse-cavalli'
      preLoaderRoute: typeof AuthenticatedCorseCavalliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversioni': {
      id: '/_authenticated/conversioni'
      path: '/conversioni'
      fullPath: '/conversioni'
      preLoaderRoute: typeof AuthenticatedConversioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cittadini': {
      id: '/_authenticated/cittadini'
      path: '/cittadini'
      fullPath: '/cittadini'
      preLoaderRoute: typeof AuthenticatedCittadiniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cassette': {
      id: '/_authenticated/cassette'
      path: '/cassette'
      fullPath: '/cassette'
      preLoaderRoute: typeof AuthenticatedCassetteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/badge': {
      id: '/_authenticated/badge'
      path: '/badge'
      fullPath: '/badge'
      preLoaderRoute: typeof AuthenticatedBadgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBadgeRoute: typeof AuthenticatedBadgeRoute
  AuthenticatedCassetteRoute: typeof AuthenticatedCassetteRoute
  AuthenticatedCittadiniRoute: typeof AuthenticatedCittadiniRoute
  AuthenticatedConversioniRoute: typeof AuthenticatedConversioniRoute
  AuthenticatedCorseCavalliRoute: typeof AuthenticatedCorseCavalliRoute
  AuthenticatedRuoliRoute: typeof AuthenticatedRuoliRoute
  AuthenticatedSerateRoute: typeof AuthenticatedSerateRoute
  AuthenticatedServiziRoute: typeof AuthenticatedServiziRoute
  AuthenticatedUtentiRoute: typeof AuthenticatedUtentiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBadgeRoute: AuthenticatedBadgeRoute,
  AuthenticatedCassetteRoute: AuthenticatedCassetteRoute,
  AuthenticatedCittadiniRoute: AuthenticatedCittadiniRoute,
  AuthenticatedConversioniRoute: AuthenticatedConversioniRoute,
  AuthenticatedCorseCavalliRoute: AuthenticatedCorseCavalliRoute,
  AuthenticatedRuoliRoute: AuthenticatedRuoliRoute,
  AuthenticatedSerateRoute: AuthenticatedSerateRoute,
  AuthenticatedServiziRoute: AuthenticatedServiziRoute,
  AuthenticatedUtentiRoute: AuthenticatedUtentiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
