// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    return next({
      context: {
        supabase: supabaseAdmin,
        userId: "mock-user-id-1234",
        claims: {
          sub: "mock-user-id-1234",
          email: "beppemonti84@gmail.com",
          user_metadata: { username: "admin", display_name: "Amministratore" },
        },
      },
    });
  },
);
