// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { mockDbProxy, mockAuthProxy } from "./mock-proxy";

class MockPostgrestBuilder {
  private table: string;
  private operation: "select" | "insert" | "update" | "delete" = "select";
  private selectColumns: string = "*";
  private filters: Array<{ column: string; value: any; op: "eq" | "neq" | "in" }> = [];
  private orderBy: { column: string; ascending: boolean } | null = null;
  private limitCount: number | null = null;
  private insertData: any = null;
  private updateData: any = null;
  private isMaybeSingle = false;
  private isSingle = false;

  constructor(table: string) {
    this.table = table;
  }

  select(columns: string = "*") {
    if (this.operation !== "insert" && this.operation !== "update" && this.operation !== "delete") {
      this.operation = "select";
    }
    this.selectColumns = columns;
    return this;
  }

  insert(data: any) {
    this.operation = "insert";
    this.insertData = data;
    return this;
  }

  upsert(data: any) {
    this.operation = "upsert" as any;
    this.insertData = data;
    return this;
  }

  update(data: any) {
    this.operation = "update";
    this.updateData = data;
    return this;
  }

  delete() {
    this.operation = "delete";
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push({ column, value, op: "eq" });
    return this;
  }

  neq(column: string, value: any) {
    this.filters.push({ column, value, op: "neq" });
    return this;
  }

  in(column: string, values: any[]) {
    this.filters.push({ column, value: values, op: "in" });
    return this;
  }

  is(column: string, value: any) {
    this.filters.push({ column, value, op: "is" as any });
    return this;
  }

  order(column: string, { ascending = true } = {}) {
    this.orderBy = { column, ascending };
    return this;
  }

  limit(limit: number) {
    this.limitCount = limit;
    return this;
  }

  maybeSingle() {
    this.isMaybeSingle = true;
    return this;
  }

  single() {
    this.isSingle = true;
    return this;
  }

  async execute() {
    const payload = {
      table: this.table,
      operation: this.operation,
      selectColumns: this.selectColumns,
      filters: this.filters,
      orderBy: this.orderBy,
      limitCount: this.limitCount,
      insertData: this.insertData,
      updateData: this.updateData,
      isMaybeSingle: this.isMaybeSingle,
      isSingle: this.isSingle,
    };

    try {
      const res = await mockDbProxy({ data: payload });
      return res || { data: null, error: null };
    } catch (e: any) {
      console.warn("[Supabase Client] Errore di rete o server:", e);
      return {
        data: null,
        error: { message: e?.message || "Impossibile contattare il server API" },
      };
    }
  }

  then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
    return this.execute().then(onfulfilled, onrejected);
  }
}

function setCookie(name: string, value: string, days: number) {
  if (typeof document === "undefined") return;
  let expires = "";
  if (days) {
    const date = new Date();
    date.setTime(date.getTime() + days * 24 * 60 * 60 * 1000);
    expires = "; expires=" + date.toUTCString();
  }
  const isHttps = typeof window !== "undefined" && window.location.protocol === "https:";
  const flags = isHttps ? "; SameSite=None; Secure" : "";
  document.cookie = `${name}=${value || ""}${expires}; path=/${flags}`;
}

function eraseCookie(name: string) {
  if (typeof document === "undefined") return;
  document.cookie = name + "=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;";
}

class MockSupabaseClient {
  private listeners: Set<(event: string, session: any) => void> = new Set();
  private cachedSession: any = null;
  private hasLoadedSession = false;

  private notify(event: string, session: any) {
    this.cachedSession = session;
    this.hasLoadedSession = true;
    this.listeners.forEach((cb) => {
      try {
        cb(event, session);
      } catch (e) {
        console.error("[Supabase Mock] Error in auth state listener:", e);
      }
    });
  }

  auth = {
    onAuthStateChange: (cb: any) => {
      this.listeners.add(cb);
      // Fire an initial async event that won't trigger router.invalidate, or keep it safe
      this.auth.getSession().then(({ data }) => {
        cb("INITIAL_SESSION", data.session);
      });
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              this.listeners.delete(cb);
            },
          },
        },
      };
    },
    getSession: async () => {
      if (this.hasLoadedSession) {
        if (this.cachedSession?.user?.id) {
          setCookie("casino_userId", this.cachedSession.user.id, 1);
        }
        return { data: { session: this.cachedSession }, error: null };
      }

      if (typeof window !== "undefined") {
        const storedStr = localStorage.getItem("casinorevenge_session");
        if (storedStr) {
          try {
            const parsed = JSON.parse(storedStr);
            const now = Date.now();
            const oneDayMs = 24 * 60 * 60 * 1000;
            if (parsed.createdAt && now - parsed.createdAt < oneDayMs) {
              this.cachedSession = parsed.session;
              this.hasLoadedSession = true;
              setCookie("casino_userId", parsed.session.user.id, 1);
              return { data: { session: parsed.session }, error: null };
            } else {
              localStorage.removeItem("casinorevenge_session");
              eraseCookie("casino_userId");
            }
          } catch (e) {
            console.error("Error parsing stored session:", e);
          }
        }
      }

      this.cachedSession = null;
      this.hasLoadedSession = true;
      return { data: { session: null }, error: null };
    },
    getUser: async () => {
      const { data } = await this.auth.getSession();
      return { data: { user: data.session?.user ?? null }, error: null };
    },
    signUp: async (data: any) => {
      try {
        const res = await mockAuthProxy({ data: { action: "signUp", payload: data } });
        if (res?.data?.session) {
          if (typeof window !== "undefined") {
            localStorage.setItem(
              "casinorevenge_session",
              JSON.stringify({
                session: res.data.session,
                createdAt: Date.now(),
              }),
            );
            setCookie("casino_userId", res.data.session.user.id, 1);
          }
          this.notify("SIGNED_IN", res.data.session);
        }
        return res || { data: null, error: { message: "Errore di connessione al server" } };
      } catch (err: any) {
        console.error("[Supabase Auth] Sign up error:", err);
        return {
          data: null,
          error: { message: err?.message || "Errore durante la registrazione" },
        };
      }
    },
    signInWithPassword: async (data: any) => {
      try {
        const res = await mockAuthProxy({ data: { action: "signInWithPassword", payload: data } });
        if (res?.data?.session) {
          if (typeof window !== "undefined") {
            localStorage.setItem(
              "casinorevenge_session",
              JSON.stringify({
                session: res.data.session,
                createdAt: Date.now(),
              }),
            );
            setCookie("casino_userId", res.data.session.user.id, 1);
          }
          this.notify("SIGNED_IN", res.data.session);
        }
        return res || { data: null, error: { message: "Errore di connessione al server" } };
      } catch (err: any) {
        console.error("[Supabase Auth] Login error:", err);
        return {
          data: null,
          error: { message: err?.message || "Errore durante il login" },
        };
      }
    },
    signOut: async () => {
      try {
        await mockAuthProxy({ data: { action: "signOut" } });
      } catch (err: any) {
        // Ignore network errors on signout
      }
      if (typeof window !== "undefined") {
        localStorage.removeItem("casinorevenge_session");
        eraseCookie("casino_userId");
      }
      this.notify("SIGNED_OUT", null);
      return { error: null };
    },
  };

  from(table: string) {
    return new MockPostgrestBuilder(table);
  }

  async rpc(name: string, args: any) {
    const payload = { operation: "rpc", name, args };
    try {
      const res = await mockDbProxy({ data: payload });
      return res || { data: null, error: null };
    } catch (e: any) {
      console.error("[Supabase Client] RPC error:", e);
      return { data: null, error: { message: e?.message || "Errore RPC" } };
    }
  }
}

function createSupabaseClient() {
  console.log("[Supabase] Consistently using the Firestore-backed local mock client");
  return new MockSupabaseClient() as any;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
