// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { mockDbProxy, mockAuthProxy } from "./mock-proxy";

class MockPostgrestBuilder {
  private table: string;
  private operation: "select" | "insert" | "update" | "delete" = "select";
  private selectColumns: string = "*";
  private filters: Array<{ column: string; value: any; op: "eq" | "neq" | "in" }> = [];
  private orderBy: { column: string; ascending: boolean } | null = null;
  private limitCount: number | null = null;
  private insertData: any = null;
  private updateData: any = null;
  private isMaybeSingle = false;
  private isSingle = false;

  constructor(table: string) {
    this.table = table;
  }

  select(columns: string = "*") {
    if (this.operation !== "insert" && this.operation !== "update" && this.operation !== "delete") {
      this.operation = "select";
    }
    this.selectColumns = columns;
    return this;
  }

  insert(data: any) {
    this.operation = "insert";
    this.insertData = data;
    return this;
  }

  update(data: any) {
    this.operation = "update";
    this.updateData = data;
    return this;
  }

  delete() {
    this.operation = "delete";
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push({ column, value, op: "eq" });
    return this;
  }

  neq(column: string, value: any) {
    this.filters.push({ column, value, op: "neq" });
    return this;
  }

  in(column: string, values: any[]) {
    this.filters.push({ column, value: values, op: "in" });
    return this;
  }

  is(column: string, value: any) {
    this.filters.push({ column, value, op: "is" as any });
    return this;
  }

  order(column: string, { ascending = true } = {}) {
    this.orderBy = { column, ascending };
    return this;
  }

  limit(limit: number) {
    this.limitCount = limit;
    return this;
  }

  maybeSingle() {
    this.isMaybeSingle = true;
    return this;
  }

  single() {
    this.isSingle = true;
    return this;
  }

  async execute() {
    return await mockDbProxy({
      data: {
        table: this.table,
        operation: this.operation,
        selectColumns: this.selectColumns,
        filters: this.filters,
        orderBy: this.orderBy,
        limitCount: this.limitCount,
        insertData: this.insertData,
        updateData: this.updateData,
        isMaybeSingle: this.isMaybeSingle,
        isSingle: this.isSingle,
      },
    });
  }

  then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
    return this.execute().then(onfulfilled, onrejected);
  }
}

class MockSupabaseClient {
  private listeners: Set<(event: string, session: any) => void> = new Set();
  private cachedSession: any = null;
  private hasLoadedSession = false;

  private notify(event: string, session: any) {
    this.cachedSession = session;
    this.hasLoadedSession = true;
    this.listeners.forEach((cb) => {
      try {
        cb(event, session);
      } catch (e) {
        console.error("[Supabase Mock] Error in auth state listener:", e);
      }
    });
  }

  auth = {
    onAuthStateChange: (cb: any) => {
      this.listeners.add(cb);
      // Fire an initial async event that won't trigger router.invalidate, or keep it safe
      this.auth.getSession().then(({ data }) => {
        cb("INITIAL_SESSION", data.session);
      });
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              this.listeners.delete(cb);
            },
          },
        },
      };
    },
    getSession: async () => {
      if (this.hasLoadedSession) {
        return { data: { session: this.cachedSession }, error: null };
      }
      const res = await mockAuthProxy({ data: { action: "getSession" } });
      this.cachedSession = res.data?.session ?? null;
      this.hasLoadedSession = true;
      return res;
    },
    getUser: async () => {
      const { data } = await this.auth.getSession();
      return { data: { user: data.session?.user ?? null }, error: null };
    },
    signUp: async (data: any) => {
      const res = await mockAuthProxy({ data: { action: "signUp", payload: data } });
      if (res.data?.session) {
        this.notify("SIGNED_IN", res.data.session);
      }
      return res;
    },
    signInWithPassword: async (data: any) => {
      const res = await mockAuthProxy({ data: { action: "signInWithPassword", payload: data } });
      if (res.data?.session) {
        this.notify("SIGNED_IN", res.data.session);
      }
      return res;
    },
    signOut: async () => {
      const res = await mockAuthProxy({ data: { action: "signOut" } });
      this.notify("SIGNED_OUT", null);
      return res;
    },
  };

  from(table: string) {
    return new MockPostgrestBuilder(table);
  }

  async rpc(name: string, args: any) {
    return await mockDbProxy({ data: { operation: "rpc", name, args } });
  }
}

function createSupabaseClient() {
  console.log("[Supabase] Consistently using the Firestore-backed local mock client");
  return new MockSupabaseClient() as any;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
