// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { queryMockDb, handleMockAuth } from "./mock-db.server";

class MockPostgrestServerBuilder {
  private table: string;
  private operation: "select" | "insert" | "update" | "delete" = "select";
  private selectColumns: string = "*";
  private filters: Array<{ column: string; value: any; op: "eq" | "neq" | "in" }> = [];
  private orderBy: { column: string; ascending: boolean } | null = null;
  private limitCount: number | null = null;
  private insertData: any = null;
  private updateData: any = null;
  private isMaybeSingle = false;
  private isSingle = false;

  constructor(table: string) {
    this.table = table;
  }

  select(columns: string = "*") {
    if (this.operation !== "insert" && this.operation !== "update" && this.operation !== "delete") {
      this.operation = "select";
    }
    this.selectColumns = columns;
    return this;
  }

  insert(data: any) {
    this.operation = "insert";
    this.insertData = data;
    return this;
  }

  upsert(data: any) {
    this.operation = "upsert" as any;
    this.insertData = data;
    return this;
  }

  update(data: any) {
    this.operation = "update";
    this.updateData = data;
    return this;
  }

  delete() {
    this.operation = "delete";
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push({ column, value, op: "eq" });
    return this;
  }

  neq(column: string, value: any) {
    this.filters.push({ column, value, op: "neq" });
    return this;
  }

  in(column: string, values: any[]) {
    this.filters.push({ column, value: values, op: "in" });
    return this;
  }

  is(column: string, value: any) {
    this.filters.push({ column, value, op: "is" as any });
    return this;
  }

  order(column: string, { ascending = true } = {}) {
    this.orderBy = { column, ascending };
    return this;
  }

  limit(limit: number) {
    this.limitCount = limit;
    return this;
  }

  maybeSingle() {
    this.isMaybeSingle = true;
    return this;
  }

  single() {
    this.isSingle = true;
    return this;
  }

  async execute() {
    return queryMockDb({
      table: this.table,
      operation: this.operation,
      selectColumns: this.selectColumns,
      filters: this.filters,
      orderBy: this.orderBy,
      limitCount: this.limitCount,
      insertData: this.insertData,
      updateData: this.updateData,
      isMaybeSingle: this.isMaybeSingle,
      isSingle: this.isSingle,
    });
  }

  then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
    return this.execute().then(onfulfilled, onrejected);
  }
}

class MockSupabaseServerClient {
  auth = {
    admin: {
      listUsers: async () => {
        const db = await queryMockDb({ table: "profiles", operation: "select" });
        const users = (db.data || []).map((p: any) => ({
          id: p.id,
          email: `${p.username}@revenge.local`,
          created_at: p.created_at,
          user_metadata: { username: p.username, display_name: p.display_name },
        }));
        return { data: { users }, error: null };
      },
      createUser: async (payload: any) => {
        return await handleMockAuth({ action: "signUp", payload });
      },
      deleteUser: async (userId: string) => {
        await queryMockDb({
          table: "profiles",
          operation: "delete",
          filters: [{ column: "id", value: userId, op: "eq" }],
        });
        await queryMockDb({
          table: "user_roles",
          operation: "delete",
          filters: [{ column: "user_id", value: userId, op: "eq" }],
        });
        await queryMockDb({
          table: "user_custom_roles",
          operation: "delete",
          filters: [{ column: "user_id", value: userId, op: "eq" }],
        });
        return { error: null };
      },
      updateUserById: async (userId: string, payload: any) => {
        return { error: null };
      },
    },
  };

  from(table: string) {
    return new MockPostgrestServerBuilder(table);
  }

  async rpc(name: string, args: any) {
    return queryMockDb({ operation: "rpc", name, args });
  }
}

function createSupabaseAdminClient() {
  console.log("[Supabase Admin] Consistently using the Firestore-backed server mock client");
  return new MockSupabaseServerClient() as any;
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
